#page title
page_title                                :                                           # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1557964462                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    :                                           # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : # assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Safely preserve and secure artwork

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Ryan                                
your_link                                 :                      
your_city                                 : the USA                                
email_address                             : hello@artbox.app
facebook_username                         :                                           
instagram_username                        : artboxtheapp 
twitter_username                          : artboxtheapp
github_username                           : 
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : An Essential Tool
    description                           : We get you -- keep those special projects while keeping a decluttered house.
    fontawesome_icon_name                 : user-friends
    
  - title                                 : Apple Exclusive
    description                           : Built natively for iPhone and iPad
    fontawesome_icon_name                 : mobile

  - title                                 : Privacy First
    description                           : Privacy-focused services like iCloud mean your data is YOUR data.
    fontawesome_icon_name                 : lock

  - title                                 : Intuitive Design
    description                           : Built for ease of use and simple navigation.
    fontawesome_icon_name                 : thumbs-up

  - title                                 : Unlimited Profiles
    description                           : Create an unlimited amount of private artist profiles.
    fontawesome_icon_name                 : user-tag
  
  - title                                 : Favorites View
    description                           : Not all projects are created equal -- easily find your favorites.
    fontawesome_icon_name                 : star

  - title                                 : iCloud Sync
    description                           : Profiles and projects are automatically synced and backed up to iCloud.
    fontawesome_icon_name                 : cloud

  - title                                 : Security
    description                           : Lock your app with biometric authentication.
    fontawesome_icon_name                 : face-viewfinder

  - title                                 : Widgets
    description                           : Feature your artists' artwork right on your homescreen.
    fontawesome_icon_name                 : images

  - title                                 : # New Feature Title
    description                           : # New Feature Description
    fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.
    
    
# Press Review List                       Edit, add or remove press reviews to be presented.
pressreviews                              :

  - author                                : Oliver Haslam
    quote                                 : If you have young kids you really ought to check this out.
    sitename                              : iMore
    siteurl                               : https://www.imore.com/artbox-gives-you-somewhere-save-all-your-kids-artwork
    fontawesome_icon_name                 : newspaper
    
  - author                                : Shifrah Combiths
    quote                                 : Artbox solves the problem of what to do with all your kids’ “masterpieces.”
    sitename                              : Apartment Therapy
    siteurl                               : https://www.apartmenttherapy.com/artbox-app-review-kids-art-36870551
    fontawesome_icon_name                 : newspaper
  
  - author                                : Raheela James
    quote                                 : It is the perfect app for the Minimalist Parent, who doesn't want any clutter.
    sitename                              : Mommy's Business 101
    siteurl                               : https://www.instagram.com/p/CHbfa3jjydJ/?igshid=1mjwd55c74l2c/
    fontawesome_icon_name                 : newspaper
    
  - author                                : Adi Unsworth
    quote                                 : A simple and effective artwork storage and sharing tool.
    sitename                              : Declutter Designs
    siteurl                               : https://www.declutterdesigns.com.au/post/saving-kids-artworks-using-an-app-four-reviews
    fontawesome_icon_name                 : newspaper



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : white                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#9B71EC"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#9B71EC"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
